### ISSUE TITLE
Campaign launch failure

### ISSUE THREAD

**Issue by theflexbird** [OpusCapita/onboarding#159]
1) workflow.js L214 join campaign to campaignContact and then inject 'c_' + campaign.customerId as tenantId into the email template

2) adjust email template to use tenantId in landingpage and transition api urls

3) /public/landingpage/:tenantId/:campaignId/:contactId
* strip the tenant prefix c_ from the tenantId in order to generate customerId (edited)

4) exactly as 3), strip c_ and get customerId, error message if not c_

5) /api/campaigns/start/:campaignId
add customerId to the query as where condition, get customerId from current user (req.opuscapita.userData('customerid'))

**Comment by gr4per** [comment]
On 8th June we identified following issues requiring fixes:

* workflow.js L214 join campaign to campaignContact and then inject 'c_' + campaign.customerId as tenantId into the email template

* adjust email template to use tenantId in landingpage and transition api urls

* /public/landingpage/:tenantId/:campaignId/:contactId

strip the tenant prefix c_ from the tenantId in order to generate customerId (edited)

*/public/transition/ exactly as 3), strip c_ and get customerId, error message if not c_

* /api/campaigns/start/:campaignId
add customerId to the query as where condition, get customerId from current user (req.opuscapita.userData('customerid'))
