### ISSUE TITLE
Onboarding crashes almost immediately

### ISSUE THREAD

**Issue by celber** [OpusCapita/onboarding#201]
steps to reproduce:
- stop and update everything
- run docker-compose up -d --build
- wait 2 minutes

Result: onboarding crashed without errors
Expected result: Onboarding start
![monosnap 2017-07-06 07-54-35](https://user-images.githubusercontent.com/2181779/27897439-9fd9df86-6220-11e7-8bc5-a91098ebd696.png)
up

HEAD: 5b2de624f0ba4267c5d4d43d38c4fb6ad94a5e35

**Comment by theflexbird** [comment]
**System**: Linux ubuntu 4.10.0-28-generic
**dokcer version** 17.05.0-ce
**docker-compose version** 1.14.0

It seems like onboarding is working. It(onboarding) cannot communicate with auth.
<img width="1135" alt="zrzut ekranu 2017-08-03 o 14 15 18" src="https://user-images.githubusercontent.com/1525388/28921437-3d0ce906-7856-11e7-8406-09413e58d809.png">

Immediately after boot I have services down:
- onboarding_blob_1
- onboarding_customer_1
- onboarding_isodata_1
- onboarding_networktest_1

**Comment by kwierchris** [comment]
I am working with that almost every day and it sometimes has some hiccups but should be coming up after at least two or three tries. Sometimes it needs a docker-compose down or a docker-compose pull.

Blob is not coming up if the ENVs BLOB_ACCOUNT and BLOB_KEY are missing because they are secret and have to be passed over the command line when doing docker-compose up.

Networktest I've never seen running.

Customer should come up.

**Comment by theflexbird** [comment]
Main is failing because of timeout. It is trying to connect to **onboarding_mysql_1** but somehow it is not able to.

<img width="1440" alt="zrzut ekranu 2017-08-07 o 11 37 40" src="https://user-images.githubusercontent.com/1525388/29021275-4287cf6a-7b65-11e7-9a0c-fec92af11c46.png">
