### ISSUE TITLE
If Voucher exists for supplier, onboarding fails

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/onboarding#359]
We came across during test.
Supplier is created new in scope of user registration but and existing einvoice-send.Voucher record is still in db with matching supplier id.

This actually caused the campaignContact to magically switch to status onboarded without any logs in Kibana.
However, we saw logs about updates to status registered before that.

**Comment by kekonen** [comment]
Right now, trying to reproduce the error on the last BNP state, in the following manner:

1. Creating campaign
2. Creating a Voucher in the DB, the same as it is naturally created by the following supplier registering process. Example: ```INSERT INTO `bnp`.`Voucher` (`id`, `customerId`, `supplierId`, `status`, `createdBy`, `changedBy`, `createdOn`) VALUES ('1', 'ncc', 'examplecompany', 'new', 'svc_onboarding', '', '2017-09-25 08:49:40');```
3. Registering the supplier with the same `supplierId` (Company name), so that the generated Voucher would be the same as added to the DB on step 2.
4. At this point, just after submission of Supplier Registration form, the contact that had a status **registered** now has status **errorGeneratingVoucher**
![image](https://user-images.githubusercontent.com/11177808/30800835-a0ba2cde-a1e1-11e7-9eda-9d6c7aaef4ff.png)
The contact's status above is not changed after finishing the registration process and other manipulations. 
Playing around with creation a Voucher (as in step 2) with differently edited relevant fields is not making any result similar to Topic Starter's. 

I would propose to go through the tests one more time with the current set up, as the random commit may have fixed the problem. Otherwise, go through the test flow manually.
