### ISSUE TITLE
Supplier can access "create a campaign"-page

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#361]
**Steps to reproduce:**
1. Go to address https://develop.businessnetwork.opuscapita.com/onboarding/create
2. Log in as a supplier

**Expected result:**
User is logged in but is forwarded to some "supplier dashboard"
**Actual result:**
Create campaign page is opened and the user can actually start a campaign. 
**Other info:**
There are also other pages the supplier can access by writing the url in browser address bar. Malicious users could try to harm the system using this security problem.

**Comment by nczeranka** [comment]
It is a feature of our application, that links to editors, dashboards, etc. can be called directly. 
But Harming the system should not be possible at all, though apis on the server will only work with proper customer or supplier assignment - depending on the action.

With the new Onboarding system, we have added a couple of checks so that the ui will not be shown at all.

Future plans:  Permissions on ui components and menus.
