### ISSUE TITLE
Importing contacts does not import country

### ISSUE THREAD

**Issue by blomqsu1** [OpusCapita/onboarding#418]
Steps to reproduce: 
1. Go to contacts
2. Import one contact from csv file where country is mentioned. 
3. Check the country
**Expected result:** 
Country is what was specified in csv file. 
**Actual result:** 
Country is empty. 
**Other information:** 
Tried at least country and state of these possibilities-> Country : country, state, countryCode, Land, Staat

**Comment by kekonen** [comment]
The problem with Country mapping is not an actual problem. A county is successfully imported, but it should be formatted into proper country code (i.e. `SE` for Sweden, `GE` for Germany, etc.).

However, there was found another similar problem: `email` field in a contact is remaining empty after a successful import. The source of the problem is usage of field synonyms for contact parsing.

**Comment by nczeranka** [comment]
As a first enhancement, we improved the "country" label to refer to "ISO 3166-1 alpha-2".
Besides of it we will enhance the importer to raise a validation error - see #473
